### ISSUE TITLE
Unable to playback lidar data recorded as ROS Packets

### ISSUE THREAD

**Issue by nsteve2407** [RoboSense-LiDAR/rslidar_sdk#148]
## What
Recorded a ros2 bag with the robosense driver config set to the following
```
common:
  msg_source: 1
  send_packet_ros: true
  send_point_cloud_ros: false
  send_packet_proto: false
  send_point_cloud_proto: false
lidar:
  - driver:
      lidar_type: RSBP
      msop_port: X
      difop_port: X
      start_angle: 0
      end_angle: 360
      min_distance: 0.2
      max_distance: 200
      use_lidar_clock: false
      host_address: X.X.X.X
    ros:
      ros_frame_id: lidar
      ros_recv_packet_topic: /robosense/lidar/packets
      ros_send_packet_topic: /robosense/lidar/packets
      ros_send_point_cloud_topic: /robosense/lidar/points
``` 

When I try to playback the packet data in the bag file I used the following config:
```
common:
  msg_source: 2
  send_packet_ros: false
  send_point_cloud_ros: true
  send_packet_proto: false
  send_point_cloud_proto: false
lidar:
  - driver:
      lidar_type: RSBP
      msop_port: X
      difop_port: X
      start_angle: 0
      end_angle: 360
      min_distance: 0.2
      max_distance: 200
      use_lidar_clock: false
      host_address: X.X.X.X
    ros:
      ros_frame_id: lidar
      ros_recv_packet_topic: /robosense/lidar/packets
      ros_send_packet_topic: /robosense/lidar/packets
      ros_send_point_cloud_topic: /robosense/lidar/points
``` 

During playback I see the node `/rslidar_packets_source_0` subscribing to the `/robosense/lidar/packets` but no data is published to the `/robosense/lidar/points` topic.
Maybe similar to issue https://github.com/RoboSense-LiDAR/rslidar_sdk/issues/112
