### ISSUE TITLE
First published header timestamp is zero, if ts_first_point is set to true on Airy

### ISSUE THREAD

**Issue by georgflick** [RoboSense-LiDAR/rslidar_sdk#179]
On the Robosense Airy, if you enable `ts_first_point`, the first published pointcloud has a header zero timestamp.

```
header:
  stamp:
    sec: 0
    nanosec: 0
```

but it should be set to the time of the first point and not zero.
