### ISSUE TITLE
rs-16 and rs-m1 supporting problem

### ISSUE THREAD

**Issue by simulacrus** [RoboSense-LiDAR/rslidar_sdk#19]
0. Configuration rslidar_sdk

  ```yaml
common:
  msg_source: 1                                         #0: not use Lidar
                                                        #1: packet message comes from online Lidar
                                                        #2: packet message comes from ROS or ROS2
                                                        #3: packet message comes from Pcap file
                                                        #4: packet message comes from Protobuf-UDP
                                                        #5: point cloud comes from Protobuf-UDP
  send_packet_ros: false                                #true: Send packets through ROS or ROS2(Used to record packet)
  send_point_cloud_ros: true                            #true: Send point cloud through ROS or ROS2
  send_packet_proto: false                              #true: Send packets through Protobuf-UDP
  send_point_cloud_proto: false                         #true: Send point cloud through Protobuf-UDP
  pcap_path: /home/robosense/lidar.pcap                 #The path of pcap file

lidar:

#top lidr info

  - driver:
      lidar_type: RS32             #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: /lidar_top         #Frame id of message
      msop_port: 6690              #Msop port of lidar
      difop_port: 7789             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp  
    ros:
      ros_recv_packet_topic: /rslidar_top_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_top_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /lidar_top/points      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
      packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to
  
# left lidar info

  - driver:
      lidar_type: RS16             #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: /lidar_left         #Frame id of message
      msop_port: 5590              #Msop port of lidar
      difop_port: 6689             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp  
    ros:
      ros_recv_packet_topic: /rslidar_left_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_left_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /lidar_left/points      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
      packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to

# right lidar info

  - driver:
      lidar_type: RS16             #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: /lidar_right         #Frame id of message
      msop_port: 4490              #Msop port of lidar
      difop_port: 5589             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp  
    ros:
      ros_recv_packet_topic: /rslidar_right_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_right_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /lidar_right/points      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
      packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to


# front lidar info

  - driver:
      lidar_type: RSM1             #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: /lidar_front         #Frame id of message
      msop_port: 6699              #Msop port of lidar
      difop_port: 7788             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                   #False-- Use the system clock as the timestamp  
    ros:
      ros_recv_packet_topic: /rslidar_front_packets          #Topic used to receive lidar packets from ROS
      ros_send_packet_topic: /rslidar_front_packets          #Topic used to send lidar packets through ROS
      ros_send_point_cloud_topic: /lidar_front/points      #Topic used to send point cloud through ROS
    proto:
      point_cloud_recv_port: 60021                     #Port number used for receiving point cloud 
      point_cloud_send_port: 60021                     #Port number which the point cloud will be send to
      msop_recv_port: 60022                            #Port number used for receiving lidar msop packets
      msop_send_port: 60022                            #Port number which the msop packets will be send to 
      difop_recv_port: 60023                           #Port number used for receiving lidar difop packets
      difop_send_port: 60023                           #Port number which the difop packets will be send to 
      point_cloud_send_ip: 127.0.0.1                   #Ip address which the point cloud will be send to 
      packet_send_ip: 127.0.0.1                        #Ip address which the lidar packets will be send to
```

  robosense sdk release 1.3.0.

1. # RS-16

After `roslaunch rslidar_sdk start.launch` and opening rviz i was confusing by periodically disappearing part of points.  
(View 1.pcd, 2.pcd, 1.png, 2.png).

[1.pcd](https://github.com/RoboSense-LiDAR/rslidar_sdk/files/6000995/1.zip)

![1](https://user-images.githubusercontent.com/79246839/108321232-ebeb3d80-71d4-11eb-95c7-2b690761ae61.png)

[2.pcd](https://github.com/RoboSense-LiDAR/rslidar_sdk/files/6000996/2.zip)

![2](https://user-images.githubusercontent.com/79246839/108321437-34a2f680-71d5-11eb-95a3-1ef64117b149.png)

Interesting that RSView show scans correctly

2.  # RS m1

There is some problem with correcting reading poins from RS MEMS by rslidar_sdk

[3.pcd](https://github.com/RoboSense-LiDAR/rslidar_sdk/files/6000999/3.zip)

![4](https://user-images.githubusercontent.com/79246839/108321624-7cc21900-71d5-11eb-83bc-106bad4c5858.png)

RSView show correcting scans

![3](https://user-images.githubusercontent.com/79246839/108321644-83e92700-71d5-11eb-801a-fc273a08f4a1.png)
