### ISSUE TITLE
Unable to Visualize RS80 PCAP data in RVIZ 

### ISSUE THREAD

**Issue by ajay1606** [RoboSense-LiDAR/rslidar_sdk#54]
Hello,

I am trying to run Visualize the RS lidars data recorded in PCAP format using ROS workspace.
By configuring the below config.yaml am able to visualize data of RS128 and RS32 without any issues.

Similiarly, If i configure configue.yaml file for RS80 (RSRubyLite) Lidar am getting points like this.

![image](https://user-images.githubusercontent.com/29722843/127942112-9c0cb638-9580-4420-bf9d-c199f8f37d3b.png)

```
lidar:
  - driver:
      lidar_type: RS80           #LiDAR type - RS16, RS32, RSBP, RS128, RS80, RSM1, RSHELIOS
      frame_id: /rslidar           #Frame id of message
      msop_port: 6699              #Msop port of lidar
      difop_port: 7788             #Difop port of lidar
      start_angle: 0               #Start angle of point cloud
      end_angle: 360               #End angle of point cloud 
      min_distance: 0.2            #Minimum distance of point cloud
      max_distance: 200            #Maximum distance of point cloud
      use_lidar_clock: false       #True--Use the lidar clock as the message timestamp
                                                   #False-- Use the system clock as the timestamp  
```

Any help is much appreciated. Thanks

Regards,
Ajay
